/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { DeployedContract } from "./DeployedContract";
import { DeployedContractList } from "./DeployedContractList";
import { AugmintReserves_ABI_024b81d1a1f75241167a8a0f6e62326f } from "./types/AugmintReserves_ABI_024b81d1a1f75241167a8a0f6e62326f";
import { Exchange_ABI_d3e7f8a261b756f9c40da097608b21cd } from "./types/Exchange_ABI_d3e7f8a261b756f9c40da097608b21cd";
import { FeeAccount_ABI_67db260db12738df3cced3511d34c65c } from "./types/FeeAccount_ABI_67db260db12738df3cced3511d34c65c";
import { InterestEarnedAccount_ABI_11b039ce783db308e1a9b5f46f05824f } from "./types/InterestEarnedAccount_ABI_11b039ce783db308e1a9b5f46f05824f";
import { LoanManager_ABI_fdf5fde95aa940c6dbfb8353c572c5fb } from "./types/LoanManager_ABI_fdf5fde95aa940c6dbfb8353c572c5fb";
import { Locker_ABI_f59526398823aef0f0c1454d0b6b4eac } from "./types/Locker_ABI_f59526398823aef0f0c1454d0b6b4eac";
import { Migrations_ABI_78141a323f4a8416891b06a0a2b90065 } from "./types/Migrations_ABI_78141a323f4a8416891b06a0a2b90065";
import { MonetarySupervisor_ABI_7f500b43397413e97de925528187f9cd } from "./types/MonetarySupervisor_ABI_7f500b43397413e97de925528187f9cd";
import { PreTokenProxy_ABI_dd40c0d39ea8bad8a388522667a84687 } from "./types/PreTokenProxy_ABI_dd40c0d39ea8bad8a388522667a84687";
import { PreToken_ABI_7f69e33e7b345c780ac9e43f391437d9 } from "./types/PreToken_ABI_7f69e33e7b345c780ac9e43f391437d9";
import { Rates_ABI_73a17ebb0acc71773371c6a8e1c8e6ce } from "./types/Rates_ABI_73a17ebb0acc71773371c6a8e1c8e6ce";
import { StabilityBoardProxy_ABI_dd40c0d39ea8bad8a388522667a84687 } from "./types/StabilityBoardProxy_ABI_dd40c0d39ea8bad8a388522667a84687";
import { TokenAEur_ABI_2ea91d34a7bfefc8f38ef0e8a5ae24a5 } from "./types/TokenAEur_ABI_2ea91d34a7bfefc8f38ef0e8a5ae24a5";

export const AugmintReserves: DeployedContractList = new DeployedContractList([
    new DeployedContract<AugmintReserves_ABI_024b81d1a1f75241167a8a0f6e62326f>({
        abiFileName: "AugmintReserves_ABI_024b81d1a1f75241167a8a0f6e62326f",
        abiHash: "024b81d1a1f75241167a8a0f6e62326f",
        contractName: "AugmintReserves",
        deployedAddress: "0x33bec125657470e53887400666bdeed360b2168a",
        generatedAt: 1540828363253,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<AugmintReserves_ABI_024b81d1a1f75241167a8a0f6e62326f>({
        abiFileName: "AugmintReserves_ABI_024b81d1a1f75241167a8a0f6e62326f",
        abiHash: "024b81d1a1f75241167a8a0f6e62326f",
        contractName: "AugmintReserves",
        deployedAddress: "0xc036a1dd59ac55e2fb6b3d7416cb4ecc44605834",
        generatedAt: 1539869702347,
        latestInAbi: false,
        current: false
    })
]);
export const Exchange: DeployedContractList = new DeployedContractList([
    new DeployedContract<Exchange_ABI_d3e7f8a261b756f9c40da097608b21cd>({
        abiFileName: "Exchange_ABI_d3e7f8a261b756f9c40da097608b21cd",
        abiHash: "d3e7f8a261b756f9c40da097608b21cd",
        contractName: "Exchange",
        deployedAddress: "0xe5d6d0c107eae79d2d30798f252ac6ff5ecad459",
        generatedAt: 1540828363331,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<Exchange_ABI_d3e7f8a261b756f9c40da097608b21cd>({
        abiFileName: "Exchange_ABI_d3e7f8a261b756f9c40da097608b21cd",
        abiHash: "d3e7f8a261b756f9c40da097608b21cd",
        contractName: "Exchange",
        deployedAddress: "0xdf47d51028daff13424f42523fdac73079ab901b",
        generatedAt: 1539869702438,
        latestInAbi: false,
        current: false
    })
]);
export const FeeAccount: DeployedContractList = new DeployedContractList([
    new DeployedContract<FeeAccount_ABI_67db260db12738df3cced3511d34c65c>({
        abiFileName: "FeeAccount_ABI_67db260db12738df3cced3511d34c65c",
        abiHash: "67db260db12738df3cced3511d34c65c",
        contractName: "FeeAccount",
        deployedAddress: "0xaa16ede9093bb4140e2715ed9a1e41cdfd9d9c29",
        generatedAt: 1540828363259,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<FeeAccount_ABI_67db260db12738df3cced3511d34c65c>({
        abiFileName: "FeeAccount_ABI_67db260db12738df3cced3511d34c65c",
        abiHash: "67db260db12738df3cced3511d34c65c",
        contractName: "FeeAccount",
        deployedAddress: "0xb77f9cdda72eec47a57793be088c7b523f6b5014",
        generatedAt: 1539869702354,
        latestInAbi: false,
        current: false
    })
]);
export const InterestEarnedAccount: DeployedContractList = new DeployedContractList([
    new DeployedContract<InterestEarnedAccount_ABI_11b039ce783db308e1a9b5f46f05824f>({
        abiFileName: "InterestEarnedAccount_ABI_11b039ce783db308e1a9b5f46f05824f",
        abiHash: "11b039ce783db308e1a9b5f46f05824f",
        contractName: "InterestEarnedAccount",
        deployedAddress: "0xdd96979697b76787b5062084eea60bf929ddd844",
        generatedAt: 1540828363264,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<InterestEarnedAccount_ABI_11b039ce783db308e1a9b5f46f05824f>({
        abiFileName: "InterestEarnedAccount_ABI_11b039ce783db308e1a9b5f46f05824f",
        abiHash: "11b039ce783db308e1a9b5f46f05824f",
        contractName: "InterestEarnedAccount",
        deployedAddress: "0x489cbf1674b575e6dfcff0a4f2bbc74f7e9dde28",
        generatedAt: 1539869702360,
        latestInAbi: false,
        current: false
    })
]);
export const LoanManager: DeployedContractList = new DeployedContractList([
    new DeployedContract<LoanManager_ABI_fdf5fde95aa940c6dbfb8353c572c5fb>({
        abiFileName: "LoanManager_ABI_fdf5fde95aa940c6dbfb8353c572c5fb",
        abiHash: "fdf5fde95aa940c6dbfb8353c572c5fb",
        contractName: "LoanManager",
        deployedAddress: "0x3792c5a5077dacfe331b81837ef73bc0ea721d90",
        generatedAt: 1540828363304,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<LoanManager_ABI_fdf5fde95aa940c6dbfb8353c572c5fb>({
        abiFileName: "LoanManager_ABI_fdf5fde95aa940c6dbfb8353c572c5fb",
        abiHash: "fdf5fde95aa940c6dbfb8353c572c5fb",
        contractName: "LoanManager",
        deployedAddress: "0x6cb7731c78e677f85942b5f1d646b3485e5820c1",
        generatedAt: 1539869702404,
        latestInAbi: false,
        current: false
    })
]);
export const Locker: DeployedContractList = new DeployedContractList([
    new DeployedContract<Locker_ABI_f59526398823aef0f0c1454d0b6b4eac>({
        abiFileName: "Locker_ABI_f59526398823aef0f0c1454d0b6b4eac",
        abiHash: "f59526398823aef0f0c1454d0b6b4eac",
        contractName: "Locker",
        deployedAddress: "0xc0b97fe5cad0d43d0c974c4e9a00312dc661f8ab",
        generatedAt: 1540828363317,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<Locker_ABI_f59526398823aef0f0c1454d0b6b4eac>({
        abiFileName: "Locker_ABI_f59526398823aef0f0c1454d0b6b4eac",
        abiHash: "f59526398823aef0f0c1454d0b6b4eac",
        contractName: "Locker",
        deployedAddress: "0x6d84ab6c385b827e58c358d078ac7b1c61b68821",
        generatedAt: 1539869702423,
        latestInAbi: false,
        current: false
    })
]);
export const Migrations: DeployedContractList = new DeployedContractList([
    new DeployedContract<Migrations_ABI_78141a323f4a8416891b06a0a2b90065>({
        abiFileName: "Migrations_ABI_78141a323f4a8416891b06a0a2b90065",
        abiHash: "78141a323f4a8416891b06a0a2b90065",
        contractName: "Migrations",
        deployedAddress: "0xc9a7258b2b1ea36ce735793e4816ad949532c9fd",
        generatedAt: 1539869702323,
        latestInAbi: true,
        current: true
    })
]);
export const MonetarySupervisor: DeployedContractList = new DeployedContractList([
    new DeployedContract<MonetarySupervisor_ABI_7f500b43397413e97de925528187f9cd>({
        abiFileName: "MonetarySupervisor_ABI_7f500b43397413e97de925528187f9cd",
        abiHash: "7f500b43397413e97de925528187f9cd",
        contractName: "MonetarySupervisor",
        deployedAddress: "0x4a7f6ecbe8b324a55b85adcc45313a412957b8ea",
        generatedAt: 1540828363281,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<MonetarySupervisor_ABI_7f500b43397413e97de925528187f9cd>({
        abiFileName: "MonetarySupervisor_ABI_7f500b43397413e97de925528187f9cd",
        abiHash: "7f500b43397413e97de925528187f9cd",
        contractName: "MonetarySupervisor",
        deployedAddress: "0xcec3574eca89409b15a8a72a6e737c4171457871",
        generatedAt: 1539869702380,
        latestInAbi: false,
        current: false
    })
]);
export const PreToken: DeployedContractList = new DeployedContractList([
    new DeployedContract<PreToken_ABI_7f69e33e7b345c780ac9e43f391437d9>({
        abiFileName: "PreToken_ABI_7f69e33e7b345c780ac9e43f391437d9",
        abiHash: "7f69e33e7b345c780ac9e43f391437d9",
        contractName: "PreToken",
        deployedAddress: "0xa7b67e7e3e7f1e76e8d799a690f675abeb85c788",
        generatedAt: 1539869702470,
        latestInAbi: true,
        current: true
    })
]);
export const PreTokenProxy: DeployedContractList = new DeployedContractList([
    new DeployedContract<PreTokenProxy_ABI_dd40c0d39ea8bad8a388522667a84687>({
        abiFileName: "PreTokenProxy_ABI_dd40c0d39ea8bad8a388522667a84687",
        abiHash: "dd40c0d39ea8bad8a388522667a84687",
        contractName: "PreTokenProxy",
        deployedAddress: "0xb7cae2c48f3f34b9696fd290001dea16b299498a",
        generatedAt: 1539869702452,
        latestInAbi: true,
        current: true
    })
]);
export const Rates: DeployedContractList = new DeployedContractList([
    new DeployedContract<Rates_ABI_73a17ebb0acc71773371c6a8e1c8e6ce>({
        abiFileName: "Rates_ABI_73a17ebb0acc71773371c6a8e1c8e6ce",
        abiHash: "73a17ebb0acc71773371c6a8e1c8e6ce",
        contractName: "Rates",
        deployedAddress: "0xee8c7a3e99945a5207dca026504d67527125da9c",
        generatedAt: 1540828363242,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<Rates_ABI_73a17ebb0acc71773371c6a8e1c8e6ce>({
        abiFileName: "Rates_ABI_73a17ebb0acc71773371c6a8e1c8e6ce",
        abiHash: "73a17ebb0acc71773371c6a8e1c8e6ce",
        contractName: "Rates",
        deployedAddress: "0xdfa3a0aeb9645a55b684cb3ace8c42d018405bda",
        generatedAt: 1539869702334,
        latestInAbi: false,
        current: false
    })
]);
export const StabilityBoardProxy: DeployedContractList = new DeployedContractList([
    new DeployedContract<StabilityBoardProxy_ABI_dd40c0d39ea8bad8a388522667a84687>({
        abiFileName: "StabilityBoardProxy_ABI_dd40c0d39ea8bad8a388522667a84687",
        abiHash: "dd40c0d39ea8bad8a388522667a84687",
        contractName: "StabilityBoardProxy",
        deployedAddress: "0xa612de13b629a1ff790c1f4e41d0422d2bb50a30",
        generatedAt: 1540828363339,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<StabilityBoardProxy_ABI_dd40c0d39ea8bad8a388522667a84687>({
        abiFileName: "StabilityBoardProxy_ABI_dd40c0d39ea8bad8a388522667a84687",
        abiHash: "dd40c0d39ea8bad8a388522667a84687",
        contractName: "StabilityBoardProxy",
        deployedAddress: "0x50d281c28846576eaaf679ab6f3baac52b776e72",
        generatedAt: 1539869702447,
        latestInAbi: false,
        current: false
    })
]);
export const TokenAEur: DeployedContractList = new DeployedContractList([
    new DeployedContract<TokenAEur_ABI_2ea91d34a7bfefc8f38ef0e8a5ae24a5>({
        abiFileName: "TokenAEur_ABI_2ea91d34a7bfefc8f38ef0e8a5ae24a5",
        abiHash: "2ea91d34a7bfefc8f38ef0e8a5ae24a5",
        contractName: "TokenAEur",
        deployedAddress: "0x79065a165ec09e6a89d584a14872802717fe12a3",
        generatedAt: 1540828363268,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<TokenAEur_ABI_2ea91d34a7bfefc8f38ef0e8a5ae24a5>({
        abiFileName: "TokenAEur_ABI_2ea91d34a7bfefc8f38ef0e8a5ae24a5",
        abiHash: "2ea91d34a7bfefc8f38ef0e8a5ae24a5",
        contractName: "TokenAEur",
        deployedAddress: "0x0557183334edc23a666201edc6b0aa2787e2ad3f",
        generatedAt: 1539869702366,
        latestInAbi: false,
        current: false
    })
]);
