/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { DeployedContract } from "./DeployedContract";
import { DeployedContractList } from "./DeployedContractList";
import { AugmintReserves_ABI_024b81d1a1f75241167a8a0f6e62326f } from "./types/AugmintReserves_ABI_024b81d1a1f75241167a8a0f6e62326f";
import { Exchange_ABI_d3e7f8a261b756f9c40da097608b21cd } from "./types/Exchange_ABI_d3e7f8a261b756f9c40da097608b21cd";
import { FeeAccount_ABI_67db260db12738df3cced3511d34c65c } from "./types/FeeAccount_ABI_67db260db12738df3cced3511d34c65c";
import { InterestEarnedAccount_ABI_11b039ce783db308e1a9b5f46f05824f } from "./types/InterestEarnedAccount_ABI_11b039ce783db308e1a9b5f46f05824f";
import { LoanManager_ABI_fdf5fde95aa940c6dbfb8353c572c5fb } from "./types/LoanManager_ABI_fdf5fde95aa940c6dbfb8353c572c5fb";
import { Locker_ABI_f59526398823aef0f0c1454d0b6b4eac } from "./types/Locker_ABI_f59526398823aef0f0c1454d0b6b4eac";
import { Migrations_ABI_78141a323f4a8416891b06a0a2b90065 } from "./types/Migrations_ABI_78141a323f4a8416891b06a0a2b90065";
import { MonetarySupervisor_ABI_7f500b43397413e97de925528187f9cd } from "./types/MonetarySupervisor_ABI_7f500b43397413e97de925528187f9cd";
import { PreTokenProxy_ABI_dd40c0d39ea8bad8a388522667a84687 } from "./types/PreTokenProxy_ABI_dd40c0d39ea8bad8a388522667a84687";
import { PreToken_ABI_7f69e33e7b345c780ac9e43f391437d9 } from "./types/PreToken_ABI_7f69e33e7b345c780ac9e43f391437d9";
import { Rates_ABI_73a17ebb0acc71773371c6a8e1c8e6ce } from "./types/Rates_ABI_73a17ebb0acc71773371c6a8e1c8e6ce";
import { StabilityBoardProxy_ABI_dd40c0d39ea8bad8a388522667a84687 } from "./types/StabilityBoardProxy_ABI_dd40c0d39ea8bad8a388522667a84687";
import { TokenAEur_ABI_2ea91d34a7bfefc8f38ef0e8a5ae24a5 } from "./types/TokenAEur_ABI_2ea91d34a7bfefc8f38ef0e8a5ae24a5";

export const AugmintReserves: DeployedContractList = new DeployedContractList([
    new DeployedContract<AugmintReserves_ABI_024b81d1a1f75241167a8a0f6e62326f>({
        abiFileName: "AugmintReserves_ABI_024b81d1a1f75241167a8a0f6e62326f",
        abiHash: "024b81d1a1f75241167a8a0f6e62326f",
        contractName: "AugmintReserves",
        deployedAddress: "0x1b9441428f9e682bab4f9cc70fdf50adcc3411f4",
        generatedAt: 1554402698821,
        latestInAbi: true,
        current: true
    })
]);
export const Exchange: DeployedContractList = new DeployedContractList([
    new DeployedContract<Exchange_ABI_d3e7f8a261b756f9c40da097608b21cd>({
        abiFileName: "Exchange_ABI_d3e7f8a261b756f9c40da097608b21cd",
        abiHash: "d3e7f8a261b756f9c40da097608b21cd",
        contractName: "Exchange",
        deployedAddress: "0xfacea53a04befcc6c9246eb3951814cfee2a1415",
        generatedAt: 1554402699082,
        latestInAbi: true,
        current: true
    })
]);
export const FeeAccount: DeployedContractList = new DeployedContractList([
    new DeployedContract<FeeAccount_ABI_67db260db12738df3cced3511d34c65c>({
        abiFileName: "FeeAccount_ABI_67db260db12738df3cced3511d34c65c",
        abiHash: "67db260db12738df3cced3511d34c65c",
        contractName: "FeeAccount",
        deployedAddress: "0xf5efcaa78f5656f7ddc971bc5d51a08b5f161573",
        generatedAt: 1554402698833,
        latestInAbi: true,
        current: true
    })
]);
export const InterestEarnedAccount: DeployedContractList = new DeployedContractList([
    new DeployedContract<InterestEarnedAccount_ABI_11b039ce783db308e1a9b5f46f05824f>({
        abiFileName: "InterestEarnedAccount_ABI_11b039ce783db308e1a9b5f46f05824f",
        abiHash: "11b039ce783db308e1a9b5f46f05824f",
        contractName: "InterestEarnedAccount",
        deployedAddress: "0x1efb52b6aacc403cc9d762282b2aec1b066931c5",
        generatedAt: 1554402698842,
        latestInAbi: true,
        current: true
    })
]);
export const LoanManager: DeployedContractList = new DeployedContractList([
    new DeployedContract<LoanManager_ABI_fdf5fde95aa940c6dbfb8353c572c5fb>({
        abiFileName: "LoanManager_ABI_fdf5fde95aa940c6dbfb8353c572c5fb",
        abiHash: "fdf5fde95aa940c6dbfb8353c572c5fb",
        contractName: "LoanManager",
        deployedAddress: "0x213135c85437c23bc529a2ee9c2980646c332fcb",
        generatedAt: 1554402699018,
        latestInAbi: true,
        current: true
    })
]);
export const Locker: DeployedContractList = new DeployedContractList([
    new DeployedContract<Locker_ABI_f59526398823aef0f0c1454d0b6b4eac>({
        abiFileName: "Locker_ABI_f59526398823aef0f0c1454d0b6b4eac",
        abiHash: "f59526398823aef0f0c1454d0b6b4eac",
        contractName: "Locker",
        deployedAddress: "0x26b4ababb98fcadd579f28e9c30931bbbe66fc88",
        generatedAt: 1554402699059,
        latestInAbi: true,
        current: true
    })
]);
export const Migrations: DeployedContractList = new DeployedContractList([
    new DeployedContract<Migrations_ABI_78141a323f4a8416891b06a0a2b90065>({
        abiFileName: "Migrations_ABI_78141a323f4a8416891b06a0a2b90065",
        abiHash: "78141a323f4a8416891b06a0a2b90065",
        contractName: "Migrations",
        deployedAddress: "0xd217ac4354211cda27dd4027b5e223280f885ad3",
        generatedAt: 1554402698781,
        latestInAbi: true,
        current: true
    })
]);
export const MonetarySupervisor: DeployedContractList = new DeployedContractList([
    new DeployedContract<MonetarySupervisor_ABI_7f500b43397413e97de925528187f9cd>({
        abiFileName: "MonetarySupervisor_ABI_7f500b43397413e97de925528187f9cd",
        abiHash: "7f500b43397413e97de925528187f9cd",
        contractName: "MonetarySupervisor",
        deployedAddress: "0x1555469d4a6c063a13ff1e12ca4ab00f5f1b7320",
        generatedAt: 1554402698873,
        latestInAbi: true,
        current: true
    })
]);
export const PreToken: DeployedContractList = new DeployedContractList([
    new DeployedContract<PreToken_ABI_7f69e33e7b345c780ac9e43f391437d9>({
        abiFileName: "PreToken_ABI_7f69e33e7b345c780ac9e43f391437d9",
        abiHash: "7f69e33e7b345c780ac9e43f391437d9",
        contractName: "PreToken",
        deployedAddress: "0xbed57eb0b4232da0cddd3c9c27490fc0759e0a01",
        generatedAt: 1554402699131,
        latestInAbi: true,
        current: true
    })
]);
export const PreTokenProxy: DeployedContractList = new DeployedContractList([
    new DeployedContract<PreTokenProxy_ABI_dd40c0d39ea8bad8a388522667a84687>({
        abiFileName: "PreTokenProxy_ABI_dd40c0d39ea8bad8a388522667a84687",
        abiHash: "dd40c0d39ea8bad8a388522667a84687",
        contractName: "PreTokenProxy",
        deployedAddress: "0x8b639dc72f3e640c0d6bc19497fbc7b5160d0463",
        generatedAt: 1554402699103,
        latestInAbi: true,
        current: true
    })
]);
export const Rates: DeployedContractList = new DeployedContractList([
    new DeployedContract<Rates_ABI_73a17ebb0acc71773371c6a8e1c8e6ce>({
        abiFileName: "Rates_ABI_73a17ebb0acc71773371c6a8e1c8e6ce",
        abiHash: "73a17ebb0acc71773371c6a8e1c8e6ce",
        contractName: "Rates",
        deployedAddress: "0xb0a2a8e846b66c7384f52635cecef5280f766c8b",
        generatedAt: 1554402698800,
        latestInAbi: true,
        current: true
    })
]);
export const StabilityBoardProxy: DeployedContractList = new DeployedContractList([
    new DeployedContract<StabilityBoardProxy_ABI_dd40c0d39ea8bad8a388522667a84687>({
        abiFileName: "StabilityBoardProxy_ABI_dd40c0d39ea8bad8a388522667a84687",
        abiHash: "dd40c0d39ea8bad8a388522667a84687",
        contractName: "StabilityBoardProxy",
        deployedAddress: "0xd3ef19679c2dbbf3b8e2077c61b88f5e9c6178eb",
        generatedAt: 1554402699094,
        latestInAbi: true,
        current: true
    })
]);
export const TokenAEur: DeployedContractList = new DeployedContractList([
    new DeployedContract<TokenAEur_ABI_2ea91d34a7bfefc8f38ef0e8a5ae24a5>({
        abiFileName: "TokenAEur_ABI_2ea91d34a7bfefc8f38ef0e8a5ae24a5",
        abiHash: "2ea91d34a7bfefc8f38ef0e8a5ae24a5",
        contractName: "TokenAEur",
        deployedAddress: "0xbbecff5db2f9cccc936895121802fc15053344c6",
        generatedAt: 1554402698849,
        latestInAbi: true,
        current: true
    })
]);
