/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { DeployedContract } from "./DeployedContract";
import { DeployedContractList } from "./DeployedContractList";
import { AugmintReserves_ABI_024b81d1a1f75241167a8a0f6e62326f } from "./types/AugmintReserves_ABI_024b81d1a1f75241167a8a0f6e62326f";
import { AugmintReserves_ABI_fe74b7986dafb00f221486e790fc70ec } from "./types/AugmintReserves_ABI_fe74b7986dafb00f221486e790fc70ec";
import { Exchange_ABI_b2a23202a9a0f04755a186896c2b56eb } from "./types/Exchange_ABI_b2a23202a9a0f04755a186896c2b56eb";
import { Exchange_ABI_c28de2392aea85ef2aa1b108fce6568c } from "./types/Exchange_ABI_c28de2392aea85ef2aa1b108fce6568c";
import { Exchange_ABI_d3e7f8a261b756f9c40da097608b21cd } from "./types/Exchange_ABI_d3e7f8a261b756f9c40da097608b21cd";
import { FeeAccount_ABI_67db260db12738df3cced3511d34c65c } from "./types/FeeAccount_ABI_67db260db12738df3cced3511d34c65c";
import { InterestEarnedAccount_ABI_11b039ce783db308e1a9b5f46f05824f } from "./types/InterestEarnedAccount_ABI_11b039ce783db308e1a9b5f46f05824f";
import { LoanManager_ABI_ec709c3341045caa3a75374b8cfc7286 } from "./types/LoanManager_ABI_ec709c3341045caa3a75374b8cfc7286";
import { LoanManager_ABI_fdf5fde95aa940c6dbfb8353c572c5fb } from "./types/LoanManager_ABI_fdf5fde95aa940c6dbfb8353c572c5fb";
import { Locker_ABI_619ff7809b73aead28176fe6317953c3 } from "./types/Locker_ABI_619ff7809b73aead28176fe6317953c3";
import { Locker_ABI_f59526398823aef0f0c1454d0b6b4eac } from "./types/Locker_ABI_f59526398823aef0f0c1454d0b6b4eac";
import { Migrations_ABI_78141a323f4a8416891b06a0a2b90065 } from "./types/Migrations_ABI_78141a323f4a8416891b06a0a2b90065";
import { MonetarySupervisor_ABI_54d27fedd8bf3010ad5509866a42c053 } from "./types/MonetarySupervisor_ABI_54d27fedd8bf3010ad5509866a42c053";
import { MonetarySupervisor_ABI_7f500b43397413e97de925528187f9cd } from "./types/MonetarySupervisor_ABI_7f500b43397413e97de925528187f9cd";
import { PreTokenProxy_ABI_19ab69b650e28b2dd211d3851893f91f } from "./types/PreTokenProxy_ABI_19ab69b650e28b2dd211d3851893f91f";
import { PreTokenProxy_ABI_dd40c0d39ea8bad8a388522667a84687 } from "./types/PreTokenProxy_ABI_dd40c0d39ea8bad8a388522667a84687";
import { PreToken_ABI_10eebbb51a771cfd3473475169a569f1 } from "./types/PreToken_ABI_10eebbb51a771cfd3473475169a569f1";
import { PreToken_ABI_7f69e33e7b345c780ac9e43f391437d9 } from "./types/PreToken_ABI_7f69e33e7b345c780ac9e43f391437d9";
import { Rates_ABI_73a17ebb0acc71773371c6a8e1c8e6ce } from "./types/Rates_ABI_73a17ebb0acc71773371c6a8e1c8e6ce";
import { StabilityBoardProxy_ABI_19ab69b650e28b2dd211d3851893f91f } from "./types/StabilityBoardProxy_ABI_19ab69b650e28b2dd211d3851893f91f";
import { StabilityBoardProxy_ABI_dd40c0d39ea8bad8a388522667a84687 } from "./types/StabilityBoardProxy_ABI_dd40c0d39ea8bad8a388522667a84687";
import { TokenAEur_ABI_2ea91d34a7bfefc8f38ef0e8a5ae24a5 } from "./types/TokenAEur_ABI_2ea91d34a7bfefc8f38ef0e8a5ae24a5";
import { TokenAEur_ABI_9aa81519ec45a52d3f8f1a1a83d25c74 } from "./types/TokenAEur_ABI_9aa81519ec45a52d3f8f1a1a83d25c74";

export const AugmintReserves: DeployedContractList = new DeployedContractList([
    new DeployedContract<AugmintReserves_ABI_024b81d1a1f75241167a8a0f6e62326f>({
        abiFileName: "AugmintReserves_ABI_024b81d1a1f75241167a8a0f6e62326f",
        abiHash: "024b81d1a1f75241167a8a0f6e62326f",
        contractName: "AugmintReserves",
        deployedAddress: "0x65f30f8dd20c707c1938ccad7416c7381e6eb9c8",
        generatedAt: 1542199933027,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<AugmintReserves_ABI_fe74b7986dafb00f221486e790fc70ec>({
        abiFileName: "AugmintReserves_ABI_fe74b7986dafb00f221486e790fc70ec",
        abiHash: "fe74b7986dafb00f221486e790fc70ec",
        contractName: "AugmintReserves",
        deployedAddress: "0x633cb544b2ef1bd9269b2111fd2b66fc05cd3477",
        generatedAt: 1528725269111,
        latestInAbi: true,
        current: false
    })
]);
export const Exchange: DeployedContractList = new DeployedContractList([
    new DeployedContract<Exchange_ABI_d3e7f8a261b756f9c40da097608b21cd>({
        abiFileName: "Exchange_ABI_d3e7f8a261b756f9c40da097608b21cd",
        abiHash: "d3e7f8a261b756f9c40da097608b21cd",
        contractName: "Exchange",
        deployedAddress: "0xc670ffbfa21c37481fb4ef2ea2249b9b78d2b073",
        generatedAt: 1542199933099,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<Exchange_ABI_c28de2392aea85ef2aa1b108fce6568c>({
        abiFileName: "Exchange_ABI_c28de2392aea85ef2aa1b108fce6568c",
        abiHash: "c28de2392aea85ef2aa1b108fce6568c",
        contractName: "Exchange",
        deployedAddress: "0xafea54badf7a68f93c2235b5f4cc8f02a2b55edd",
        generatedAt: 1536758455240,
        latestInAbi: true,
        current: false
    }),
    new DeployedContract<Exchange_ABI_c28de2392aea85ef2aa1b108fce6568c>({
        abiFileName: "Exchange_ABI_c28de2392aea85ef2aa1b108fce6568c",
        abiHash: "c28de2392aea85ef2aa1b108fce6568c",
        contractName: "Exchange",
        deployedAddress: "0xeae7d30bcd44f27d58985b56add007fcee254abd",
        generatedAt: 1535111839856,
        latestInAbi: false,
        current: false
    }),
    new DeployedContract<Exchange_ABI_b2a23202a9a0f04755a186896c2b56eb>({
        abiFileName: "Exchange_ABI_b2a23202a9a0f04755a186896c2b56eb",
        abiHash: "b2a23202a9a0f04755a186896c2b56eb",
        contractName: "Exchange",
        deployedAddress: "0x8b52b019d237d0bbe8baedf219132d5254e0690b",
        generatedAt: 1528729184035,
        latestInAbi: true,
        current: false
    })
]);
export const FeeAccount: DeployedContractList = new DeployedContractList([
    new DeployedContract<FeeAccount_ABI_67db260db12738df3cced3511d34c65c>({
        abiFileName: "FeeAccount_ABI_67db260db12738df3cced3511d34c65c",
        abiHash: "67db260db12738df3cced3511d34c65c",
        contractName: "FeeAccount",
        deployedAddress: "0xe3ed84a163b9eeaf4f69b4890ae45cc52171aa7e",
        generatedAt: 1542199933033,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<FeeAccount_ABI_67db260db12738df3cced3511d34c65c>({
        abiFileName: "FeeAccount_ABI_67db260db12738df3cced3511d34c65c",
        abiHash: "67db260db12738df3cced3511d34c65c",
        contractName: "FeeAccount",
        deployedAddress: "0xf6b541e1b5e001dcc11827c1a16232759aea730a",
        generatedAt: 1528723746622,
        latestInAbi: false,
        current: false
    })
]);
export const InterestEarnedAccount: DeployedContractList = new DeployedContractList([
    new DeployedContract<InterestEarnedAccount_ABI_11b039ce783db308e1a9b5f46f05824f>({
        abiFileName: "InterestEarnedAccount_ABI_11b039ce783db308e1a9b5f46f05824f",
        abiHash: "11b039ce783db308e1a9b5f46f05824f",
        contractName: "InterestEarnedAccount",
        deployedAddress: "0xf23e0af0e41341127bb4e7b203aebca0185f9ebd",
        generatedAt: 1542199933038,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<InterestEarnedAccount_ABI_11b039ce783db308e1a9b5f46f05824f>({
        abiFileName: "InterestEarnedAccount_ABI_11b039ce783db308e1a9b5f46f05824f",
        abiHash: "11b039ce783db308e1a9b5f46f05824f",
        contractName: "InterestEarnedAccount",
        deployedAddress: "0x5c1a44e07541203474d92bdd03f803ea74f6947c",
        generatedAt: 1528725269127,
        latestInAbi: false,
        current: false
    })
]);
export const LoanManager: DeployedContractList = new DeployedContractList([
    new DeployedContract<LoanManager_ABI_fdf5fde95aa940c6dbfb8353c572c5fb>({
        abiFileName: "LoanManager_ABI_fdf5fde95aa940c6dbfb8353c572c5fb",
        abiHash: "fdf5fde95aa940c6dbfb8353c572c5fb",
        contractName: "LoanManager",
        deployedAddress: "0x1cabc34618ecf2949f0405a86353e7705e01c38b",
        generatedAt: 1542199933068,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<LoanManager_ABI_ec709c3341045caa3a75374b8cfc7286>({
        abiFileName: "LoanManager_ABI_ec709c3341045caa3a75374b8cfc7286",
        abiHash: "ec709c3341045caa3a75374b8cfc7286",
        contractName: "LoanManager",
        deployedAddress: "0xcbefaf199b800deeb9ead61f358ee46e06c54070",
        generatedAt: 1528728664245,
        latestInAbi: true,
        current: false
    })
]);
export const Locker: DeployedContractList = new DeployedContractList([
    new DeployedContract<Locker_ABI_f59526398823aef0f0c1454d0b6b4eac>({
        abiFileName: "Locker_ABI_f59526398823aef0f0c1454d0b6b4eac",
        abiHash: "f59526398823aef0f0c1454d0b6b4eac",
        contractName: "Locker",
        deployedAddress: "0x5cc161482e82f20840a4aaeb582becbcc4b539d7",
        generatedAt: 1542199933085,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<Locker_ABI_619ff7809b73aead28176fe6317953c3>({
        abiFileName: "Locker_ABI_619ff7809b73aead28176fe6317953c3",
        abiHash: "619ff7809b73aead28176fe6317953c3",
        contractName: "Locker",
        deployedAddress: "0x26438D7c52cE617dFc75A2F02eE816557f01e5Bb",
        generatedAt: 1531058032504,
        latestInAbi: true,
        current: false
    }),
    new DeployedContract<Locker_ABI_619ff7809b73aead28176fe6317953c3>({
        abiFileName: "Locker_ABI_619ff7809b73aead28176fe6317953c3",
        abiHash: "619ff7809b73aead28176fe6317953c3",
        contractName: "Locker",
        deployedAddress: "0x095c0f071fd75875a6b5a1def3f3a993f591080c",
        generatedAt: 1528728664267,
        latestInAbi: false,
        current: false
    })
]);
export const Migrations: DeployedContractList = new DeployedContractList([
    new DeployedContract<Migrations_ABI_78141a323f4a8416891b06a0a2b90065>({
        abiFileName: "Migrations_ABI_78141a323f4a8416891b06a0a2b90065",
        abiHash: "78141a323f4a8416891b06a0a2b90065",
        contractName: "Migrations",
        deployedAddress: "0xf01C976E9189BC9ba68Eda0f1Dc9d94b243C78dC",
        generatedAt: 1542199933006,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<Migrations_ABI_78141a323f4a8416891b06a0a2b90065>({
        abiFileName: "Migrations_ABI_78141a323f4a8416891b06a0a2b90065",
        abiHash: "78141a323f4a8416891b06a0a2b90065",
        contractName: "Migrations",
        deployedAddress: "0xe7e9f87805c0bec5108963d07f85e4ca5892d421",
        generatedAt: 1528721226545,
        latestInAbi: false,
        current: false
    })
]);
export const MonetarySupervisor: DeployedContractList = new DeployedContractList([
    new DeployedContract<MonetarySupervisor_ABI_7f500b43397413e97de925528187f9cd>({
        abiFileName: "MonetarySupervisor_ABI_7f500b43397413e97de925528187f9cd",
        abiHash: "7f500b43397413e97de925528187f9cd",
        contractName: "MonetarySupervisor",
        deployedAddress: "0x27484AFe9e6c332fB07F21Fac82d442EBe1D22c3",
        generatedAt: 1542199933052,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<MonetarySupervisor_ABI_54d27fedd8bf3010ad5509866a42c053>({
        abiFileName: "MonetarySupervisor_ABI_54d27fedd8bf3010ad5509866a42c053",
        abiHash: "54d27fedd8bf3010ad5509866a42c053",
        contractName: "MonetarySupervisor",
        deployedAddress: "0x1ca4f9d261707af8a856020a4909b777da218868",
        generatedAt: 1528728664213,
        latestInAbi: true,
        current: false
    })
]);
export const PreToken: DeployedContractList = new DeployedContractList([
    new DeployedContract<PreToken_ABI_7f69e33e7b345c780ac9e43f391437d9>({
        abiFileName: "PreToken_ABI_7f69e33e7b345c780ac9e43f391437d9",
        abiHash: "7f69e33e7b345c780ac9e43f391437d9",
        contractName: "PreToken",
        deployedAddress: "0x97ea02179801fa94227db5fc1d13ac4277d40920",
        generatedAt: 1542199933115,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<PreToken_ABI_10eebbb51a771cfd3473475169a569f1>({
        abiFileName: "PreToken_ABI_10eebbb51a771cfd3473475169a569f1",
        abiHash: "10eebbb51a771cfd3473475169a569f1",
        contractName: "PreToken",
        deployedAddress: "0xecb782b19be6e657ae2d88831dd98145a00d32d5",
        generatedAt: 1528719316664,
        latestInAbi: true,
        current: false
    })
]);
export const PreTokenProxy: DeployedContractList = new DeployedContractList([
    new DeployedContract<PreTokenProxy_ABI_dd40c0d39ea8bad8a388522667a84687>({
        abiFileName: "PreTokenProxy_ABI_dd40c0d39ea8bad8a388522667a84687",
        abiHash: "dd40c0d39ea8bad8a388522667a84687",
        contractName: "PreTokenProxy",
        deployedAddress: "0x8a69cf9d1d85bc150f69feb80cc34c552f5fbea9",
        generatedAt: 1542199933107,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<PreTokenProxy_ABI_19ab69b650e28b2dd211d3851893f91f>({
        abiFileName: "PreTokenProxy_ABI_19ab69b650e28b2dd211d3851893f91f",
        abiHash: "19ab69b650e28b2dd211d3851893f91f",
        contractName: "PreTokenProxy",
        deployedAddress: "0x1411b3b189b01f6e6d1ea883bffcbd3a5224934c",
        generatedAt: 1528719316657,
        latestInAbi: true,
        current: false
    })
]);
export const Rates: DeployedContractList = new DeployedContractList([
    new DeployedContract<Rates_ABI_73a17ebb0acc71773371c6a8e1c8e6ce>({
        abiFileName: "Rates_ABI_73a17ebb0acc71773371c6a8e1c8e6ce",
        abiHash: "73a17ebb0acc71773371c6a8e1c8e6ce",
        contractName: "Rates",
        deployedAddress: "0x4272dB2EB82068E898588C3D6e4B5D55c3848793",
        generatedAt: 1542199933016,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<Rates_ABI_73a17ebb0acc71773371c6a8e1c8e6ce>({
        abiFileName: "Rates_ABI_73a17ebb0acc71773371c6a8e1c8e6ce",
        abiHash: "73a17ebb0acc71773371c6a8e1c8e6ce",
        contractName: "Rates",
        deployedAddress: "0x4babbe57453e2b6af125b4e304256fcbdf744480",
        generatedAt: 1528719316443,
        latestInAbi: false,
        current: false
    })
]);
export const StabilityBoardProxy: DeployedContractList = new DeployedContractList([
    new DeployedContract<StabilityBoardProxy_ABI_dd40c0d39ea8bad8a388522667a84687>({
        abiFileName: "StabilityBoardProxy_ABI_dd40c0d39ea8bad8a388522667a84687",
        abiHash: "dd40c0d39ea8bad8a388522667a84687",
        contractName: "StabilityBoardProxy",
        deployedAddress: "0xde36a8773531406dcbeffdfd3c7b89fced7a9f84",
        generatedAt: 1542199933104,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<StabilityBoardProxy_ABI_19ab69b650e28b2dd211d3851893f91f>({
        abiFileName: "StabilityBoardProxy_ABI_19ab69b650e28b2dd211d3851893f91f",
        abiHash: "19ab69b650e28b2dd211d3851893f91f",
        contractName: "StabilityBoardProxy",
        deployedAddress: "0x4686f017d456331ed2c1de66e134d8d05b24413d",
        generatedAt: 1528719316651,
        latestInAbi: true,
        current: false
    })
]);
export const TokenAEur: DeployedContractList = new DeployedContractList([
    new DeployedContract<TokenAEur_ABI_2ea91d34a7bfefc8f38ef0e8a5ae24a5>({
        abiFileName: "TokenAEur_ABI_2ea91d34a7bfefc8f38ef0e8a5ae24a5",
        abiHash: "2ea91d34a7bfefc8f38ef0e8a5ae24a5",
        contractName: "TokenAEur",
        deployedAddress: "0xc994a2deb02543db1f48688438b9903c4b305ce3",
        generatedAt: 1542199933041,
        latestInAbi: true,
        current: true
    }),
    new DeployedContract<TokenAEur_ABI_9aa81519ec45a52d3f8f1a1a83d25c74>({
        abiFileName: "TokenAEur_ABI_9aa81519ec45a52d3f8f1a1a83d25c74",
        abiHash: "9aa81519ec45a52d3f8f1a1a83d25c74",
        contractName: "TokenAEur",
        deployedAddress: "0x86a635eccefffa70ff8a6db29da9c8db288e40d0",
        generatedAt: 1528726345122,
        latestInAbi: true,
        current: false
    })
]);
