/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractOptions, Options } from "web3-eth-contract";
import { Block } from "web3-eth";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { Callback, TransactionObject } from "./types";

export class Migrations_ABI_78141a323f4a8416891b06a0a2b90065 extends Contract {
    constructor(jsonInterface: any[], address?: string, options?: ContractOptions);
    methods: {
        setCompleted(completed: number | string): TransactionObject<void>;

        upgrade(newAddress: string): TransactionObject<void>;

        last_completed_migration(): TransactionObject<string>;
        owner(): TransactionObject<string>;
    };
    events: {
        allEvents: (
            options?: {
                filter?: object;
                fromBlock?: number | string;
                topics?: (null | string)[];
            },
            cb?: Callback<EventLog>
        ) => EventEmitter;
    };
}
