import { connectLatest } from "./utils/contractConnection";
import { EthereumConnection } from "./EthereumConnection";
/**
 * Generic Contract super class
 */
export class Contract {
    public ethereumConnection: EthereumConnection;
    public web3: any;
    public instance: any;

    get address(): string {
        return this.instance ? this.instance._address : null;
    }

    /**
     * connects to latest deployment or if address provided then  at that address
     * NB: connect by address is not implemented tyet
     * @param  {object}  ethereumConnection a connected EthereumConnection instance
     * @param  {string}  abiFile            path to the JSON abifile generated by abiniser
     * @param  {string}  address            contract address if y (not yet implemented)
     * @return {Promise}                    the web3 contract instance
     */
    public async connect(ethereumConnection: EthereumConnection, abiFile: string, address?: string) {
        if (address) {
            throw new Error(
                "Connecting to a contract at arbitary address is not supported yet. Pass no address to connect latest contract deployment at network"
            );
        }

        if (!(await ethereumConnection.isConnected())) {
            throw new Error(
                "Contract: not connected to web3 at passed ethereumConnection. call ethereumConnection.connect first"
            );
        }

        this.ethereumConnection = ethereumConnection;
        this.web3 = this.ethereumConnection.web3;

        this.instance = connectLatest(this.ethereumConnection, abiFile);

        return this.instance;
    }
}
